---
# ====== Application: Create_Tables ==========================
id: 100
identification: 
  name: Create_Tables
  alias: CREATE-TABLES
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 11706215019627303

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_DEMO

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Create_Tables

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 11707029994627305

navigation-bar: 
  implementation: List
  list: Navigation Bar # 11708238051627315
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 46808657716421

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Create_Tables

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 11701783809627292
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 46808568078797

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 11702011145627293
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 46808568078882

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 11702373066627294
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 46808568078955

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 11702627220627294
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 46808568079010

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 11702997070627295
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 46808568079063

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 11703215454627295
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 46808568079120

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 11703543281627295
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 46808568079186

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 11703806423627296
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 46808568079243

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 11704179582627297
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 46808568079377

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 11704418622627298
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 46808568079563

- # ====== Component Setting: NATIVE_IR ========================
  id: 11704793500627299
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 46808568079622

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 11705023810627300
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 46808568079738

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 11705349882627300
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 46808568079796

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 11705645329627301
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 46808568079871

