---
# ====== Application: test ===================================
id: 100
identification: 
  name: test
  alias: TEST
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 12484266092992892

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_DEMO

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: test

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 12485052099992889

navigation-bar: 
  implementation: List
  list: Navigation Bar # 12486246033992885
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 46839911564013

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: test

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 12479762265992899
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 46839911558100

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 12480031650992898
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 46839911558169

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 12480338877992898
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 46839911558223

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 12480637679992898
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 46839911558273

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 12480978531992897
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 46839911558331

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 12481206858992897
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 46839911558380

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 12481532097992896
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 46839911558440

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 12481857727992896
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 46839911558489

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 12482123561992896
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 46839911558542

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 12482461097992895
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 46839911558608

- # ====== Component Setting: NATIVE_IR ========================
  id: 12482725074992895
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 46839911558653

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 12483071462992894
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 46839911558706

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 12483322768992894
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 46839911558756

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 12483604751992893
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 46839911558809

